# Generated by Django 4.2.25 on 2025-10-22 17:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=3000.0, max_digits=10, verbose_name='Salary')),
                ('demotion_count', models.PositiveIntegerField(default=0, verbose_name='Demotion Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('is_terminated', models.BooleanField(default=False, verbose_name='Terminated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Hire Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Chef',
                'verbose_name_plural': 'Chefs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Deposit')),
                ('warnings', models.PositiveIntegerField(default=0, verbose_name='Warnings')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Spent')),
                ('order_count', models.PositiveIntegerField(default=0, verbose_name='Order Count')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP Status')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='Blacklisted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=2500.0, max_digits=10, verbose_name='Salary')),
                ('demotion_count', models.PositiveIntegerField(default=0, verbose_name='Demotion Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('is_terminated', models.BooleanField(default=False, verbose_name='Terminated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Hire Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Delivery Person',
                'verbose_name_plural': 'Delivery People',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Dish Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Image')),
                ('is_vip_only', models.BooleanField(default=False, verbose_name='VIP Only')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.chef', verbose_name='Chef')),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('vip_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='VIP Discount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Order Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.customer', verbose_name='Customer')),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.deliveryperson', verbose_name='Delivery Person')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.dish', verbose_name='Dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Hire Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('is_flagged', models.BooleanField(default=False, verbose_name='Flagged')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.customer', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Knowledge Base Item',
                'verbose_name_plural': 'Knowledge Base Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.customer', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Discussion Topic',
                'verbose_name_plural': 'Discussion Topics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Post Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.customer', verbose_name='Author')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='restaurant.discussiontopic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Discussion Post',
                'verbose_name_plural': 'Discussion Posts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bid Amount')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Selected')),
                ('justification', models.TextField(blank=True, verbose_name='Manager Justification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Bid Time')),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.deliveryperson', verbose_name='Delivery Person')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Delivery Bid',
                'verbose_name_plural': 'Delivery Bids',
                'ordering': ['bid_amount', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Compliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dismissed', 'Dismissed')], default='pending', max_length=20, verbose_name='Status')),
                ('manager_response', models.TextField(blank=True, verbose_name='Manager Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Compliment Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.chef', verbose_name='Chef')),
                ('complimenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliments_made', to='restaurant.customer', verbose_name='Complimenter')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliments_received', to='restaurant.customer', verbose_name='Customer')),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.deliveryperson', verbose_name='Delivery Person')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Compliment',
                'verbose_name_plural': 'Compliments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20, verbose_name='Status')),
                ('manager_response', models.TextField(blank=True, verbose_name='Manager Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Complaint Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.chef', verbose_name='Chef')),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_made', to='restaurant.customer', verbose_name='Complainant')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_received', to='restaurant.customer', verbose_name='Customer')),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.deliveryperson', verbose_name='Delivery Person')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DishRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('review', models.TextField(blank=True, verbose_name='Review')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Rating Time')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.customer', verbose_name='Customer')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.dish', verbose_name='Dish')),
            ],
            options={
                'verbose_name': 'Dish Rating',
                'verbose_name_plural': 'Dish Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'dish')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('review', models.TextField(blank=True, verbose_name='Review')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Rating Time')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.customer', verbose_name='Customer')),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.deliveryperson', verbose_name='Delivery Person')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Delivery Rating',
                'verbose_name_plural': 'Delivery Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'order')},
            },
        ),
    ]
