# Generated by Django 5.2.7 on 2025-11-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='bonus_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Bonus Count'),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='bonus_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Bonus Count'),
        ),
    ]
