# Generated by Django 4.2.25 on 2025-11-28 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0004_order_delivered_at_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='is_announcement',
            field=models.BooleanField(default=False, verbose_name='Is Announcement'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.customer', verbose_name='Author'),
        ),
        migrations.CreateModel(
            name='ComplaintDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(verbose_name='Dispute Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dispute Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='restaurant.complaint', verbose_name='Complaint')),
                ('disputer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Disputer')),
            ],
            options={
                'verbose_name': 'Complaint Dispute',
                'verbose_name_plural': 'Complaint Disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_pinned', models.BooleanField(default=True, verbose_name='Pinned')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
