# Generated by Django 4.2.25 on 2025-11-28 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0005_knowledgebase_is_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='source_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Source ID'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('announcement', 'Announcement'), ('post', 'Forum Post')], default='manual', max_length=20, verbose_name='Source Type'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.CreateModel(
            name='KnowledgeBaseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Score (0-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Rating Time')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='restaurant.knowledgebase', verbose_name='Knowledge Base Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Knowledge Base Rating',
                'verbose_name_plural': 'Knowledge Base Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'knowledge_base')},
            },
        ),
    ]
