# Generated by Django 4.2.25 on 2025-11-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_knowledgebase_source_id_knowledgebase_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='memo',
            field=models.TextField(blank=True, help_text='Customer special requests', null=True, verbose_name='Order Memo'),
        ),
    ]
